
BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
PREFIX = "."
CHANNEL_NAME = "MRNOOB OWNS YOU"
SPAM_MSG = "text"
CHANNEL_COUNT = 500
MSG_COUNT = 1000
CHANNEL_NAMES = ["Name1","Name2","Name3","Name4","Name5"]
USE_RANDOM = True
BAN_REASON = "Nuked by bot"
KICK_REASON = "Nuked by bot"
NUKE_ROLE = "NUKED"
NUKE_COLOR = 0xFF0000
DELETE_ROLES = True
DELETE_EMOJIS = True
DELETE_STICKERS = True

class _78:
    BOT_TOKEN = BOT_TOKEN
    PREFIX = PREFIX
    CHANNEL_NAME = CHANNEL_NAME
    SPAM_MSG = SPAM_MSG
    CHANNEL_COUNT = CHANNEL_COUNT
    MSG_COUNT = MSG_COUNT
    CHANNEL_NAMES = CHANNEL_NAMES
    USE_RANDOM = USE_RANDOM
    BAN_REASON = BAN_REASON
    KICK_REASON = KICK_REASON
    NUKE_ROLE = NUKE_ROLE
    NUKE_COLOR = NUKE_COLOR
    DELETE_ROLES = DELETE_ROLES
    DELETE_EMOJIS = DELETE_EMOJIS
    DELETE_STICKERS = DELETE_STICKERS
